### ISSUE TITLE
Failure to upload report files from executor to service.executor

### ISSUE THREAD

**Issue by pvandervelde** [pvandervelde/Sherlock#40]
Failed to upload report files for test step: 4. Error was: Nuclei.Communication.CommandInvocationFailedException: The invocation of a command failed. ---> Nuclei.Communication.FailedToSendMessageException: Failed to send the message. ---> System.ServiceModel.CommunicationException: There was an error writing to the pipe: Unrecognized error 232 (0xe8). ---> System.IO.PipeException: There was an error writing to the pipe: Unrecognized error 232 (0xe8).
   at System.ServiceModel.Channels.PipeConnection.StartSyncWrite(Byte[] buffer, Int32 offset, Int32 size, Object& holder)
   at System.ServiceModel.Channels.PipeConnection.StartSyncWrite(Byte[] buffer, Int32 offset, Int32 size)
   at System.ServiceModel.Channels.PipeConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, BufferManager bufferManager)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.PipeConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, BufferManager bufferManager)
   at System.ServiceModel.Channels.BufferedConnection.WriteNow(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, BufferManager bufferManager)
   at System.ServiceModel.Channels.BufferedConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, BufferManager bufferManager)
   at System.ServiceModel.Channels.FramingDuplexSessionChannel.OnSendCore(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.OnSend(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.OutputChannel.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Nuclei.Communication.IMessageReceivingEndpoint.AcceptMessage(ICommunicationMessage message)
   at Nuclei.Communication.RestoringMessageSendingEndpoint.Send(ICommunicationMessage message)
   --- End of inner exception stack trace ---
   at Nuclei.Communication.RestoringMessageSendingEndpoint.Send(ICommunicationMessage message)
   at Nuclei.Communication.SendingEndpoint.Send(EndpointId endpoint, ICommunicationMessage message)
   at Nuclei.Communication.CommunicationChannel.Send(EndpointId endpoint, ICommunicationMessage message)
   at Nuclei.Communication.CommunicationLayer.SendMessageAndWaitForResponse(EndpointId endpoint, ICommunicationMessage message)
   at Nuclei.Communication.CommunicationModule.SendMessageWithResponse(IConfiguration configuration, ISendDataViaChannels layer, EndpointId endpoint, ICommunicationMessage message)
   at Nuclei.Communication.CommunicationModule.<>c__DisplayClass86.<RegisterCommandHub>b__83(EndpointId endpoint, ICommunicationMessage msg)
   at Nuclei.Communication.CommandProxyBuilder.<>c__DisplayClassf.<ProxyConnectingTo>b__b(ISerializedMethodInvocation methodInvocation)
   at Nuclei.Communication.CommandSetMethodWithoutResultInterceptor.Intercept(IInvocation invocation)
   --- End of inner exception stack trace ---
   at Nuclei.Communication.CommandSetMethodWithoutResultInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ITransferTestReportDataCommandsProxy.PrepareReportFilesForTransfer(Int32 testStepIndex, EndpointId callingEndpoint, UploadToken token)
   at Sherlock.Executor.DependencyInjection.<>c__DisplayClass1.<BuildReportFileUploader>b__0(Int32 stepIndex, IDictionary`2 filesToUpload) in c:\documents\skydrive\Documents\source\sherlock\master\src\executor\DependencyInjection.cs:line 63
   at Sherlock.Executor.TestStepProcessor.TransferReportFiles(ITestSectionBuilder sectionBuilder, TestStep testStep, IEnumerable`1 additionalFilesToInclude) in c:\documents\skydrive\Documents\source\sherlock\master\src\executor\TestStepProcessor.cs:line 166

**Comment by pvandervelde** [comment]
The easy fix for this is to guard for exceptions during the file upload. However a more suitable way is to fix #34.

**Comment by pvandervelde** [comment]
Further errors after applying some of the fixes:

System.AggregateException: One or more errors occurred. ---> Nuclei.Communication.CommandInvocationFailedException: The invocation of a command failed.
at Nuclei.Communication.CommandSetMethodWithoutResultInterceptor.<>c__DisplayClass1.<CreateTask>b__0()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Sherlock.Executor.DependencyInjection.<>c__DisplayClass1.<BuildReportFileUploader>b__0(Int32 stepIndex, IDictionary`2 filesToUpload) in c:\documents\personal\source\Sherlock\src\executor\DependencyInjection.cs:line 68
at Sherlock.Executor.TestStepProcessor.TransferReportFiles(ITestSectionBuilder sectionBuilder, TestStep testStep, IEnumerable`1 additionalFilesToInclude) in c:\documents\personal\source\Sherlock\src\executor\TestStepProcessor.cs:line 166
---> (Inner Exception #0) Nuclei.Communication.CommandInvocationFailedException: The invocation of a command failed.
at Nuclei.Communication.CommandSetMethodWithoutResultInterceptor.<>c__DisplayClass1.<CreateTask>b__0()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()<---
